name:                tic
version:             0.1.0.0
github:              "ScottSedgwick/tic"
license:             BSD3
author:              "Scott Sedgwick"
maintainer:          "ssedgwick@cochlear.com"
copyright:           "Copyright 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ScottSedgwick/tic#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic
    - brick
    - vty

tests:
  tic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic
    - doctest
    - Glob
